name: Build and Release Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lowercase repository value
        run: echo "REPO_LC=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: UwUinator/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}/uwuinator:latest
            ghcr.io/${{ env.REPO_LC }}/uwuinator:${{ github.ref_name }}
